version: '3'
services:
  app:
    container_name: user-service-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./.env:/app/.env
      - ./config.json:/app/config.json
